### ISSUE TITLE
Filter the list of participants by their group name

### ISSUE THREAD

**Issue by Learnymag** [catalyst/moodle-block_dedication#99] opened 2023-11-21 10:44 UTC
In Moodle[4.1.2 (Build: 20230313)], with release block_dedication 2023112000,  I am no longer able to filter the list of participants by their group name. 
Initially, the list of participants is displayed with the group name (step 1). 
However, when I filter by group name by choosing the equal value = xx (step 2), it no longer finds any participants (step 3). 
I also noticed that if I display the list of all participants again, the group name column is no longer populated 
![Block_dedication_1](https://github.com/catalyst/moodle-block_dedication/assets/125437947/2d57db34-c0db-43b0-b8b1-2d4662b2f5ae)
![Block_dedication_2](https://github.com/catalyst/moodle-block_dedication/assets/125437947/8e9fd1c6-d23a-4d07-a12e-85d96eecb373)
(step 4). 
Tks

**Comment by danmarsden** [comment] 2023-11-21 22:36
Thasnk for the report - I can't reproduce this in a 4.3 site, I wonder if it's something specific to  Moodle 4.1 (I note you are using an old unsupported version of 4.1 that is also missing a bunch of security updates. 
Can you please upgrade to the latest version of 4.1 and provide information on the groups settings in the course? - visible/separate groups etc  - are you logged in as the site admin when reproducing this or as a teacher in the course?

**Comment by calbasi** [comment] 2024-05-11 15:10
I have the same issue here. Just updating my Moodle to the latest 4.1 version to test it further...

**Comment by calbasi** [comment] 2024-05-11 16:14
I can confirm that this issue is live in an updated (just now!) Moodle 4.1 version.

**Comment by danmarsden** [comment] 2024-05-24 07:51
I've just pushed through some improvements to the group handling - can you please download the latest version from github here to see if it solves these problems?

If not - can you please provide more information on the group settings - visible vs separate / are you logging in as an admin/teacher - can the user view all groups etc.

**Comment by Learnymag** [comment] 2024-05-27 06:43
Hello, I downloaded the latest stable version (moodle 404 stable) and I got the following error when installing the plugin on my Moodle version 4.1.2 (Build: 20230313).

![image](https://github.com/catalyst/moodle-block_dedication/assets/125437947/68ccd434-f89b-41a6-ad5b-e8831a801654)

**Comment by danmarsden** [comment] 2024-05-27 07:30
@Learnymag - you have downloaded the version for Moodle 4.4. Please download the correct version for your release.

**Comment by Learnymag** [comment] 2024-05-27 07:45
@danmarsden  Sorry. 
The filter works correctly with version 4.0, thank you

**Comment by danmarsden** [comment] 2024-05-27 08:02
great! - thanks for the confirmation, closing this off as done! :-)

**Closed as completed by danmarsden** 2024-05-27 08:02 UTC

**Comment by calbasi** [comment] 2024-05-27 15:26
I can confirm the recent version fix the issue in my hand too :-) Thank you very much
