### ISSUE TITLE
Wrong user exported on session duration

### ISSUE THREAD

**Issue by ingamr** [catalyst/moodle-block_dedication#103] opened 2024-02-07 09:01 UTC
On The block dedication report page when we click on "View session duration report". Data export is based on the current user, not the selected user.

**Comment by danmarsden** [comment] 2024-02-07 10:11
This is a duplicate of #68

**Comment by danmarsden** [comment] 2024-02-07 10:12
Sorry #98 not 68

**Closed as completed by danmarsden** 2024-02-07 10:11 UTC
