### ISSUE TITLE
Missing userid parameter when filter is used

### ISSUE THREAD

**Issue by Arvaloez** [catalyst/moodle-block_dedication#82] opened 2023-07-27 16:13 UTC
Hello,

I've been testing the plugin and there is an issue when I'm using the filter. the platform launches an issue that says that there is a missing userid parameter.
In blocks_dedication/user.php line 75 when you call the class, the filter is not getting the userid parameter. Following the documentation for that function, I'm sending the parameter using this:

$params = ['courseid' => $courseid, 'userid' => $userid];
$report = system_report_factory::create(userreport::class, context_course::instance($courseid), '', '',
            0, $params);

And, in the userreport.php, I'm receiving the parameter doing this replacement:
I removed this 
//$userid = required_param('userid', PARAM_INT);

And I changed it for this:
$userid = $this->get_parameter('userid', 0, PARAM_INT);

I did this for two functions: userreport::initialise() and userreport::can_view().

There is also a suggestion to add in the last version of the plugin, You had in the previous version, a report where you showed the total time spent by user and the average time session by user. Do you have plans to add this again?

**Comment by rmartinez-c2** [comment] 2023-10-31 14:30
@Arvaloez , your comment helped me a lot to solve the session export bug that the current version of this plugin has. Thank you very much.

**Comment by danmarsden** [comment] 2023-11-02 06:38
@Arvaloez I haven't been able to find a way to reproduce this one - adding filters to the page works fine for me... what Moodle version are you using and did you have the latest version of the code from github when you were testing this? - or were you using the version downloaded from the moodle.org plugins db?

**Comment by danmarsden** [comment] 2023-11-02 06:40
I think this may have actually been a duplicate of #79 - which was fixed at the time of your report, but only in the version available in github (not the plugins db.)

**Comment by danmarsden** [comment] 2024-05-24 07:54
As you haven't provided any further response I assume this has been fixed in the latest release - closing this one off.

**Closed as completed by danmarsden** 2024-05-24 07:54 UTC
